name: PulveSys API CI/CD
on:
  push:
    branches: ['main']
defaults:
  run:
    working-directory: ./main
jobs:
  build_run:
    runs-on: self-hosted
    env:
      DATABASE_URL: ${{secrets.PRODUCTION_DATABASE_URL}}
      JWT_SECRET_KEY: ${{secrets.JWT_SECRET_KEY}}
      PORT: ${{secrets.PRODUCTION_PORT}}
      NODE_ENV: 'production'
    strategy:
      matrix:
        node-version: [22.x]
    steps:
      - uses: actions/checkout@v4
        with:
          path: main
      - name: Setup pnpm
        uses: pnpm/action-setup@v4.1.0
        with:
          version: 10
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'pnpm'
      - name: Install dependencies
        run: pnpm i
      - name: Sync database
        run: pnpx prisma migrate deploy
      - name: Build API
        run: pnpm run build
      - name: Reload proxy server
        run: pm2 reload api.pulvesys.com --update-env
