name: PulveSys Beta API CI/CD
on:
  push:
    branches: ['develop']
defaults:
  run:
    working-directory: ./beta
jobs:
  build_run:
    runs-on: self-hosted
    env:
      DATABASE_URL: ${{secrets.DEVELOPMENT_DATABASE_URL}}
      JWT_SECRET_KEY: ${{secrets.JWT_SECRET_KEY}}
      PORT: ${{secrets.DEVELOPMENT_PORT}}
      NODE_ENV: 'beta'
    strategy:
      matrix:
        node-version: [22.x]
    steps:
      - uses: actions/checkout@v4
      - name: Setup pnpm
        uses: pnpm/action-setup@v4.1.0
        with:
          version: 10
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'pnpm'
      - name: Install dependencies
        run: pnpm i
      - name: Sync beta database
        run: pnpx prisma migrate dev
      - name: Build beta API
        run: pnpm run build
      - name: Reload beta proxy server
        run: pm2 reload beta.api.pulvesys.com --update-env
